### ISSUE TITLE
test.js newlines removed when transpiled

### ISSUE THREAD

**Issue by jdalton** [benjamn/reify#111]
While debugging something else I noticed that [test.js](https://github.com/benjamn/reify/blob/master/test/tests.js) has its newlines removed when it's transpiled resulting in
```js
module.importSync("./import-tests.js");module.importSync("./export-tests.js");module.importSync("./setter-tests.js");module.importSync("./misc-tests.js");module.importSync("./compiler-tests.js");module.importSync("./transform-tests.js");module.importSync("./babel-plugin-tests.js");module.importSync("./repl-tests.js");
```

**Comment by benjamn** [comment]
This is by design, to avoid changing line numbers and having to think about source maps. The rest of the file should still have all its whitespace, but the `module.export` and `module.importSync` calls get strung together on one line at the top of the enclosing block.

**Comment by benjamn** [comment]
Oh, I see what you mean. The file should still have eight lines, even if the final seven are just newlines.

**Comment by jdalton** [comment]
> The file should still have eight lines, even if the final seven are just newlines.

Yep, though I had assumed that imports would be changed inline too. So one `module.importSync` per line.

**Comment by benjamn** [comment]
Imports have to be hoisted to satisfy the spec (at the top level), and I don't want nested imports to behave differently from top-level imports. See this previous discussion with the Webpack author: https://github.com/benjamn/reify/pull/24.

**Comment by jdalton** [comment]
Ah ya that's right. Then the new lines it is!

**Comment by jdalton** [comment]
It looks like trailing whitespace is the issue. If you have like a `;` at the end then it preserves the whitespace. For example:
```js
import "./import-tests.js";
import "./export-tests.js";
import "./setter-tests.js";
import "./misc-tests.js";
import "./compiler-tests.js";
import "./transform-tests.js";
import "./babel-plugin-tests.js";
import "./repl-tests.js";
;
```
will become:
```js
module.importSync("./import-tests.js");module.importSync("./export-tests.js");module.importSync("./setter-tests.js");module.importSync("./misc-tests.js");module.importSync("./compiler-tests.js");module.importSync("./transform-tests.js");module.importSync("./babel-plugin-tests.js");module.importSync("./repl-tests.js");







;
```

**Comment by jdalton** [comment]
Actually nm I believe the whitespace is being preserved.
