### ISSUE TITLE
Parse optimization idea.

### ISSUE THREAD

**Issue by jdalton** [benjamn/reify#113]
From Slack:
> I think there’s another compiler optimization we could do
you can scan the source using a regular expression to find `import` and `export` tokens
then you can skip any AST nodes that don’t contain any of those tokens
and stop traversing once you know there won’t be any more tokens

**Comment by benjamn** [comment]
As proof that this idea will work, this is what Meteor [does](https://github.com/meteor/meteor/blob/759671dc6c80a8385103d44c6e41c0ab84b002a5/tools/isobuild/js-analyze.js#L46-L52) in order to scan modules for imported identifiers.

**Comment by jdalton** [comment]
This would be to optimize the import/export scan but not like assignment scans right?

**Comment by jdalton** [comment]
Cool! Let's do it! I assume you'll take point since you've implemented it in the past.
