### ISSUE TITLE
Make options.generateLegacyModuleImport more powerful

### ISSUE THREAD

**Issue by jdalton** [benjamn/reify#116]
So when the ` options.generateLegacyModuleImport` option was introduced my knee-jerk reaction was to [kill it with :fire:](https://github.com/benjamn/reify/commit/420b463d6f0031c129481198e60ebd0b8ffbcf73#commitcomment-21677418). But then I got to thinking and since reify is still pre 1.0.0 changes can happen a lot. So instead of a single toggle for legacy (which could change a couple times over) it would be rad if we allow folks to specify the actual import and export API used.

So something like:
```js
options.moduleImportCall = "module.importSync"
options.moduleExportCall = "module.export"
```
The name isn't there yet but you get the idea. That way Meteor could have "module.import" but it can be customized to taste. This also allows reify to be a bit more white label (since it will be customized for the standard esm).

**Comment by benjamn** [comment]
My one concern here is that we may want to save the `module` object as a uniquely-named temporary variable (just in case people have their own `module` variables that shadow the CommonJS object), so we would generate e.g. `_module$0.importSync`. If we did that, then this API should probably give only the method name and not include the `module.` part.

**Comment by jdalton** [comment]
Ah, no problem. Since `generateLegacyModuleImport` didn't end up getting used it can just be reverted, less complexity ftw.
