### ISSUE TITLE
async module.import.

### ISSUE THREAD

**Issue by jdalton** [benjamn/reify#117]
The basic idea for async `module.import` is
```js
Module.prototype.import = function (path) {
  return Promise.resolve().then(() => {
    const ns = Object.create(null);
    module.importSync(path, {
      "*": (value, name) => {
        ns[name] = value;
      }
    });
    return ns;
  });
};
```
~~Except that the file needs to retrievable from remote, so `http` and `https`, and that the promise won't resolve until all of the module's deps and deps of deps are loaded too. That means keeping queue of requests that need to complete.~~

**Comment by jdalton** [comment]
Turns out `http` and `https` will not likely be supported by Node out of the box so our mockup is pretty close.

**Comment by jdalton** [comment]
Ok, I got clarification, so we don't have to wait for deps of deps to be loaded either so the mockup is reeaaally close.

**Comment by benjamn** [comment]
This is fixed now, right?

**Comment by jdalton** [comment]
Yep! 🎉
