### ISSUE TITLE
IE8 throws exception on `[...].import`

### ISSUE THREAD

**Issue by ratiofu** [benjamn/reify#167]
I am working on a Meteor application that _is **not** expected to run on IE8_, but should not throw any errors when parsing the initial JS source so we can at least display a nice error message to the user. While testing in Internet Explorer 8, I encountered this exception:

```
SCRIPT1010: Expected identifier
File: modules.js, Line: 230, Column: 37
```

The "compiled" client side code for context:

```
[...]
218 # 
219 # }],"reify.js":["reify/lib/runtime",function(require,exports,module){
220 # 
221 # /////////////////////////////////////////////// ...
222 # //                                              ...
223 # // packages/modules/reify.js                    ...
224 # //                                              ...
225 # /////////////////////////////////////////////// ...
226 # 
227 # var Module = module.constructor;
228 # require("reify/lib/runtime").enable(Module);
229 # var Mp = Module.prototype;
230 # Mp.importSync = Mp.importSync || Mp.import;
231 # Mp.import = Mp.import || Mp.importSync;
230 #
[...]
```

[`import` _should_ be usable as `IdentifierName`](http://es5.github.io/#x7.6), but I guess IE8 sees it differently.

I hope I am raising this ticket in the right place, since I cannot pinpoint the code above in your current version of reify's runtime. Cheers!

**Comment by jdalton** [comment]
Hi @ratiofu!

Thanks for taking the time to file and issue and PR. IE8 is no longer supported by Microsoft or any mainstream JS library/ecosystem. It's really a dead end. If you want to support it with all its then the cost is on you to do so.

**Comment by ratiofu** [comment]
Makes sense. I knew this was a long shot. I was somewhat relying on this comment on top of `lib/runtime/index.js`:
```// This module should be maximally compatible with older JS environments,```
to see if this small change would be acceptable.
Thanks for taking a look!

**Comment by jdalton** [comment]
> `// This module should be maximally compatible with older JS environments,`

What that really means is PhantomJS 1 (until Meteor can upgrade to headless Chrome). PhantomJS 1 runs the equiv of Safari 5 (2010). IE8 (2009) misses the mark. Beyond the keyword use you'd run into other issues, since IE8 doesn't support ES5, so likely hit more JS exceptions.

**Comment by jdalton** [comment]
Something like a serverside UA sniff and redirect might be more appropriate here since IE8 does CSS/HTML wonky too.

**Comment by ratiofu** [comment]
Agreed, I considered that option as a fallback. I always feel like I am hacking when I try to get into the Meteor pipeline that sends stuff to the client. Unfortunately, for the foreseeable future my app will be in an environment where I have not control over the web server in front of it, so doing this in Meteor server-side is really my only option. Cheers!
