### ISSUE TITLE
Namespace objects should come from child module, not parent

### ISSUE THREAD

**Issue by benjamn** [benjamn/reify#171]
After [this recent commit](https://github.com/benjamn/reify/commit/39be6fe29ed1e738c6c31a33204792bc1814bb04), the `module.run` API now `Object.seal`s all namespace objects created by the module when the module is finished evaluating.

The problem is, when we create namespace objects, it's the parent module that ends up tracking them, when what we really want is for the child/imported module to be the one that creates and later seals the namespace objects.

For example, here's what I think needs to change in the `module.import` API:

```diff
commit 162418d52dc51f4311b1011524f1a91ad990e2bf
Author: Ben Newman <ben@benjamn.com>
Date:   Mon May 22 12:28:59 2017 -0400

    Use childEntry.createNs to create namepace objects.

diff --git a/lib/runtime/entry.js b/lib/runtime/entry.js
index 05683f9..05cc0e0 100644
--- a/lib/runtime/entry.js
+++ b/lib/runtime/entry.js
@@ -97,11 +97,22 @@ function addGetters(getters, constant) {
 
 Ep.addGetters = addGetters;
 
-function addNs(ns) {
+Ep.createNs = function () {
+  var ns = Object.create(null);
+
+  if (useToStringTag) {
+    Object.defineProperty(ns, Symbol.toStringTag, {
+      configurable: false,
+      enumerable: false,
+      value: "Module",
+      writable: false
+    });
+  }
+
   this.nsObjects.push(ns);
-}
 
-Ep.addNs = addNs;
+  return ns;
+};
 
 function addSetters(parent, setters, key) {
   var names = Object.keys(setters);
diff --git a/lib/runtime/index.js b/lib/runtime/index.js
index 6ebc7a5..1cba4a4 100644
--- a/lib/runtime/index.js
+++ b/lib/runtime/index.js
@@ -33,19 +33,7 @@ function enable(mod) {
 Runtime.enable = enable;
 
 function createNs() {
-  var ns = Object.create(null);
-
-  if (useToStringTag) {
-    Object.defineProperty(ns, Symbol.toStringTag, {
-      configurable: false,
-      enumerable: false,
-      value: "Module",
-      writable: false
-    });
-  }
-
-  Entry.getOrCreate(this.exports).addNs(ns);
-  return ns;
+  return Entry.getOrCreate(this.exports).createNs();
 }
 
 Rp.createNs = createNs;
@@ -84,13 +72,16 @@ function moduleImport(id) {
   var that = this;
 
   return Promise.resolve().then(function () {
-    var ns = that.createNs();
-    that.watch(that.require(id), {
+    var exported = that.require(id);
+    var ns = Entry.getOrCreate(exported).createNs();
+
+    that.watch(exported, {
       "*": function (value, name) {
         ns[name] = value;
       }
     });
-    return finishNs(ns);
+
+    return ns;
   });
 }
```

However, we also generate code that calls `module.createNs()` on the wrong (parent) module, and I'm less sure how we can fix that:
```js
import * as ns from "./child";
```
becomes
```js
const ns = module.createNs();
module.watch(require("./child"), {
  "*": (value, name) => {
    ns[name] = value;
  }
});
```
Somehow we have to let `createNs` know what child module will be managing the namespace, so perhaps we could pass something to `createNs`, like the child's `exports` object?
```js
const ns = module.createNs(require("./child"));
module.watch(require("./child"), {
  "*": (value, name) => {
    ns[name] = value;
  }
});
```
That would be enough for `createNs` to record the resulting namespace object properly with the child module, though I don't love calling `require("./child")` twice.

Any ideas?

**Comment by benjamn** [comment]
Here's a different idea:
* The parent `module` still keeps track of namespace objects.
* When the child is calling the `"*"` setter multiple times, it adds an extra call where `name` is a special `Symbol`.
* At the end of `runSetters`, where we call `parentEntry.runSetters()`, check the namespace objects of each parent, and seal the ones that have the special `Symbol` that came from this child.
* Once one of a parent's namespace objects is sealed, tell the parent to forget about it.
* Don't worry about this strategy if `Symbol` is not supported, since we don't want to be adding enumerable properties to the namespace, and the downside is just that we won't get the safety benefits of sealing namespaces in older environments.

**Comment by benjamn** [comment]
Another idea:
* Somehow pass namespace objects as arguments to `module.watch`, since it knows about the child `Entry` object, and could record the namespace with the appropriate child.

The downside here is that we would be complicating the `module.watch` API, especially since the `key` argument is supposed to be optional. Are we ok with generated code like this?
```js
const ns = module.createNs();
module.watch(require("./child"), {
  "*": (value, name) => {
    ns[name] = value;
  }
}, <key>, ns);
```

**Comment by jdalton** [comment]
> The problem is, when we create namespace objects, it's the parent module that ends up tracking them, when what we really want is for the child/imported module to be the one that creates and later seals the namespace objects.

The issue is with the `import` case only, right? 
The other one is essentially the same as it was previously. Namespace objects are created with `module.createNs()` instead of `Object.create(null)` and are finalized after their `run()` is complete. Things seem fine on that front.

**Comment by jdalton** [comment]
The `module.import` case seems OK too as the namespace object is being created in the module where it is created and used and so its being tracked there too. I'm not seeing a problem.

**Comment by jdalton** [comment]
Namespace objects are created and sealed from the modules they originate in so I think things are OK.

**Comment by jdalton** [comment]
Getting the ns values in `import` is OK because the population is synchronous. After the execution of `watch` the ns object is 100% populated and is safe to seal.
```js
module.watch(require("./child"), {
  "*": (value, name) => {
    ns[name] = value;
  }
});
```

**Comment by benjamn** [comment]
No, this includes any namespace objects that we create. I'm about to submit a pull request that fixes it.

**Comment by jdalton** [comment]
I'm not seeing how its any different than how it was handled before minus the seal bit. Or is the seal bit the issue?

**Comment by benjamn** [comment]
The question is when the sealing happens, and I assure you only the child module knows when it's done adding names to the namespace.

**Comment by jdalton** [comment]
Namespace objects are created synchronously though. You can't add props here and there to a namespace object. It's a 1 and done kinda thing.

**Comment by jdalton** [comment]
Like
```
// initialize
import * as n from "a"
// done and sealed now.
```

**Comment by benjamn** [comment]
In that example, if you're currently in a cycle with the `"a"` module, then `n` will only be populated with the properties that `"a"` has managed to export so far.

**Comment by jdalton** [comment]
Ah cycles are a mind warp for me. I'll wait for your PR to help me see the light.
