### ISSUE TITLE
Skip "default" export from `export * from "mod"`

### ISSUE THREAD

**Issue by jdalton** [benjamn/reify#184]
I noticed while [reviewing our export extension proposals](https://github.com/tc39/proposal-export-ns-from/issues/2) that by spec we should not export "default" for  `export * from "mod"`.

See https://tc39.github.io/ecma262/#sec-getexportednames.
Also mentioned in step 6 of https://tc39.github.io/ecma262/#sec-resolveexport.

This effects [runtime.makeNsSetter](https://github.com/benjamn/reify/blob/64807cff8c06bde10591ddcf1c89a3323e7b66a4/lib/runtime/index.js#L117-L121).

**Comment by benjamn** [comment]
I agree this is what the spec says, but I'm having trouble understanding why this is desirable behavior, because this breaks the ES equivalent of `module.exports = require("./other-module")` (the CommonJS "bridge" idiom). I think this is something we need to bring up at TC39.

**Comment by benjamn** [comment]
Yeah, this is totally inconsistent with the creation of module namespace objects, which uses `GetExportedNames`: https://tc39.github.io/ecma262/#sec-getmodulenamespace

Imagine if a dynamic `import(...)` couldn't access the `default` property of the imported module!

**Comment by benjamn** [comment]
Okay, I've opened an issue on the tc39/ecma262 repository. Looking forward to understanding this policy better, or getting it retracted!

**Comment by jdalton** [comment]
Thanks for raising this with the TC39.
