### ISSUE TITLE
Doesn't play nicely with require hook of flow-remove-types

### ISSUE THREAD

**Issue by tgriesser** [benjamn/reify#190]
First, thanks for the awesome tool!

I've been using both reify and [flow-remove-types](https://github.com/flowtype/flow-remove-types)'s register hook in various projects, and just tried combining them and found out they don't work together. Tried using the `babylon` parser via the `REIFY_PARSER` (as this is used by flow-remove-types) but still no luck. Babylon will parse it, unlike acorn, but it still fails at the `_compile`.

There are some comments in [flow-remove-types](https://github.com/flowtype/flow-remove-types/blob/e1d6cda061f0f6aaf24df4a439434c872748256b/register.js#L16-L22) which mention how they work with `require.extensions` and `_compile` that might be useful here?

I'm happy to dig into this a bit more with a test case or attempt at fix, but first wanted to check if this was a goal of the project. I saw that [not interfering with require.extension](https://github.com/benjamn/reify/blob/cc2eba9388a263cb0eb7411b905c46fcf927f170/BENEFITS.md#benefits) was one of the benefits, but wasn't sure if that had changed.

**Comment by jdalton** [comment]
Hi @tgriesser!

Reify now wraps the `Module._extensions` hook but should do so in a way to not block others also wanting to wrap it. As long as an original reference is called and reify has already been hooked in then it should be called.

**Comment by jdalton** [comment]
If you could dig in a bit it would be good to know what the conflict is.

**Comment by jdalton** [comment]
@tgriesser Any more info?

**Comment by tgriesser** [comment]
Haven't had a chance to dig in yet, will get to it in the next few days

**Comment by jdalton** [comment]
I figured it out. Reify hooks into `extensions['.js']` so if it hooks in after flow-remove-types then it will intercept the call and not forward it on to flow-remove-types. The issue isn't really avoided by moving to `Module._compile` because others like babel-register hook into both `extensions['.js']` and `Module._compile`.

The solution is to forward on the call. When doing so you'll need to temp wrap the file read apis so that it will return the code we want without doing another file read.

**Comment by tgriesser** [comment]
Incase anyone else finds this issue, ended up with this... not pretty having to patch `exports.compile` but it's the only place I could find that'd work for hooking in.

```js
const flowRemoveTypes = require('flow-remove-types');
const cachingCompiler = require('reify/node/caching-compiler');
const compile = cachingCompiler.compile;
cachingCompiler.compile = function _compile(content, options) {
    return compile(flowRemoveTypes(content, { all: true }).toString(), options);
};
require('reify');
```
