### ISSUE TITLE
When importing traditional CommonJS modules, register setter functions on module.exports for imported properties

### ISSUE THREAD

**Issue by benjamn** [benjamn/reify#29]
This will allow us to support live bindings for traditional CommonJS modules, where we don't have the opportunity to insert `module.runModuleSetters` calls: https://github.com/benjamn/reify/pull/24#issuecomment-223883428

**Comment by benjamn** [comment]
Obviously this assumes a working implementation of the ES5 `Object.defineProperty` API, which excludes Internet Explorer 8 and older.

**Comment by benjamn** [comment]
This would help with issues like https://github.com/d3/d3/issues/2733.

**Comment by jdalton** [comment]
Let's leave this as `wontfix` until there's demand. This feels a bit like taking a carrot away from esm.
