### ISSUE TITLE
reify with eslint

### ISSUE THREAD

**Issue by huttonr** [benjamn/reify#34]
Is there currently a workaround to allow the use reify with eslint?

Currently the parser craps out on the nested imports and I've not been able to figure out either how to loosen up the babel parser on this point or to override this.

Is this just currently unsupported?

**Comment by benjamn** [comment]
Here's an issue @rhettlivingston opened on the ESLint repo: https://github.com/eslint/eslint/issues/6472

**Comment by rhettlivingston** [comment]
I didn't get mileage with the ESLint / Espree parser path to solving the problem but did with the ESLint / babel-eslint path as seen in babel/babel-eslint/issues/327.

To get ESLint to work with nested imports and exports, first make sure you have the latest (at least 6.1.0) version of the NPM package "babel-eslint".

```bash
$npm install --save-dev babel-eslint
```

and then add the following into your ESLint configuration in package.json or .eslintrc.json:

  "parser": "babel-eslint",
  "parserOptions": {
    "allowImportExportEverywhere": true
  },

**Comment by huttonr** [comment]
@rhettlivingston 
Great, thank you!  Nice work.

@benjamn 
Perhaps a note in the README on this would be useful?  I love reify and I'm glad I can continue to lint my code despite the nested imports.
