### ISSUE TITLE
Reify not working for CLI commands ("bin" field from package.json)

### ISSUE THREAD

**Issue by almilo** [benjamn/reify#36]
Given:

``` javascript
// cli.js
#! /usr/bin/env node -r reify
import foo from './foo';
foo();
```

``` javascript
// index.js
import foo from './foo';
foo();
```

``` javascript
// foo.js
export default function () {
    console.log('foo!!');
}
```

The command:

``` sh
> node index.js
```

fails as expected, but the command:

``` sh
> node -r reify index.js
```

works without any problem.

When defining a CLI command in the "bin" field of the package.json (i.e.: "foo-test": "cli.js"), although _reify_ is required through the _-r_ option in the first line, the execution fails.

``` sh
> ./cli.js
```

What is the difference?

Thanks a lot!!
Alberto

**Comment by benjamn** [comment]
This is interesting! I'm not sure off the top of my head why these ways of invoking node would be any different, but I will definitely investigate it.

**Comment by almilo** [comment]
That would be great! I'm really finding reify useful as a solution for the es6 modules limitation in Node.js but this is a showstopper for CLI commands :(

Thanks a lot!

**Comment by olizilla** [comment]
PR #58 has a minimal fix for getting this working.
