### ISSUE TITLE
Ability to use acorn plugins

### ISSUE THREAD

**Issue by djhi** [benjamn/reify#46]
Hi @benjamn,

We have switched our old babel compilation to reify and async-to-gen for a koa v2 application and now have nice compilation times thanks to you :)

However, we are missing our beloved spread operator as acorn doesn't seems to be able to parse it. It looks like this [plugin](https://github.com/UXtemple/acorn-object-spread) would allow us to get the spread operator back but I can't figure out how to extend acorn in the reify context.

Any idea ?

**Comment by benjamn** [comment]
Acorn appears to have a new major version (4.0.3), which I suspect may add support for some ES7 features. Tests are failing right now for the simple upgrade (https://github.com/benjamn/reify/pull/45), but I should definitely look into that!

**Comment by benjamn** [comment]
There's also [precedent](https://github.com/benjamn/reify/blob/4105ed9f3cf736ca51a823b37292ed753667ec1f/lib/compiler.js#L3) for using Acorn plugins in the Reify code, though you're right that it isn't exposed to clients of Reify.

**Comment by djhi** [comment]
Looking at acorn 4.0.3, I think the `acorn-object-spread` is still needed

**Comment by jdalton** [comment]
Closing this as answered.

**Comment by ratiofu** [comment]
As @benjamn mentions above
> though you're right that it isn't exposed to clients of Reify
It appears that this is still true. Do you have any suggestions other than forking to enable (experimental ES7) `acorn` plugins with `reify`?
