### ISSUE TITLE
Capability to replace subdependencies like with proxyquire

### ISSUE THREAD

**Issue by Sanjo** [benjamn/reify#49]
For unit testing I need the capability to stub and spy on imported dependencies of my module under test. For CommonJS there is [proxyquire](https://github.com/thlorenz/proxyquire). I have this problem in the context of running tests with the Meteor test runner.

**Comment by Sanjo** [comment]
For now I run the unit and integration tests completely without the Meteor testing runner with CommonJS. I just read [Node.js, TC-39, and Modules](https://hackernoon.com/node-js-tc-39-and-modules-a1118aecf95e#95e5) which indicates that there will be hooks that make this possible. Not sure if this is already in the spec.

> There are a wide variety of scenarios where this idempotency rule causes issues. Mocking, APM, and spying for testing purposes are primary examples. Fortunately, there are a number of ways this limitation can be addressed. One approach is to add hooks into the loading phase that would allow an ESM’s exports to be wrapped. Another is for TC-39 to allow loaded ESM’s to be replaced after they are loaded. Several mechanisms are being considered here. The good news is that while intercepting ESM’s will be different than intercepting CommonJS modules, interception will be possible.

**Comment by jdalton** [comment]
Hi @Sanjo!

Behind the scenes reify wraps `Module.prototype._compile` and is executed in a CJS context. I would assume with a little bit of tinkering you should be able to re-wrap it too.
