### ISSUE TITLE
Should `import * from "some/commonjs/module"` import non-enumerable properties from module.exports?

### ISSUE THREAD

**Issue by benjamn** [benjamn/reify#60]
Currently, the namespace object is created thus:
```js
const namespace = {};
module.import("some/commonjs/module", {
  "*": function (value, name) {
    namespace[name] = value;
  }
});
```
The setter callback function is only called for `(value, name)` pairs of enumerable properties of the `some/commonjs/module`'s `exports` object.

An example of an npm package that raises this issue is https://www.npmjs.com/package/private, which (for better or worse, probably worse) defines its exports `makeAccessor` and `makeUniqueKey` as non-enumerable properties.

Presumably, if we wanted to include non-enumerable properties, the setter function would have to install them on the namespace object as non-enumerable properties as well.

It might even be best to define getters on the namespace object for the original properties, rather than copying simple data properties over.

This is perhaps too much sophistication to solve a rare usage pattern, but I wanted to record my thoughts about it anyway.

**Comment by jdalton** [comment]
We can `Object.seal` namespace objects with the help of #163 which tightens up spec compliance.
Supporting non-enumerable exports seems a bit edge case for now. We can always revisit if there's demand.
