### ISSUE TITLE
import from not working on repl

### ISSUE THREAD

**Issue by sibelius** [benjamn/reify#63]
I have this repl code https://github.com/sibelius/await-node-repl/blob/master/repl.js

using reify and a custom eval do make it work with `async await` code through babel

after this

`import faker from 'faker'` stopped working on my repl session

`const faker = require('faker')` works

.babelrc config

```json
{
  "presets": ["es2015", "stage-0"]
}
```

**Comment by benjamn** [comment]
What version of Node are you using?

**Comment by sibelius** [comment]
`v6.10.0`

**Comment by jdalton** [comment]
Later versions Reify only wrap `vm.createScript` when used inside the real Node REPL. Scripted REPL instance may require additional wiring.
