### ISSUE TITLE
reify register

### ISSUE THREAD

**Issue by thiamsantos** [benjamn/reify#65]
How can I use reify for compile the files on the fly, the same way [babel register](https://babeljs.io/docs/usage/babel-register/).

I want to use reify + [buble/register](https://gitlab.com/Rich-Harris/buble/blob/master/register.js) to run my es6 unit tests.

**Comment by jdalton** [comment]
Hi @thiamsantos!

You can use `node -r node_modules/reify/node/index.js /path/to/your/test.js`.

**Comment by thiamsantos** [comment]
Thanks @jdalton

**Comment by jedwards1211** [comment]
I'm so confused what the purpose of this package is vs. `@babel/register`
