### ISSUE TITLE
Optimized top-level parse.

### ISSUE THREAD

**Issue by jdalton** [benjamn/reify#68]
As mentioned in slack, a couple days ago @RReverser proofed out an idea to do a [top-level only parse with acorn](https://github.com/RReverser/esmod). The results are impressive.

![image](https://cloud.githubusercontent.com/assets/4303/24051357/0dcf6cc4-0aef-11e7-809c-b316f67a60d3.png)

It would be rad to be able to leverage a top level parse in reify.

**Comment by RReverser** [comment]
@benjamn I think adapting implementation should be pretty straightforward, but let me know if you need any help.

**Comment by jdalton** [comment]
I believe in @benjamn's early experiments he's seeing a 10x improvement.
So rad, thank you @RReverser!

**Comment by benjamn** [comment]
I just pushed some commits to support this use case:
* The top-level parser, based on @RReverser's `esmod` implementation: https://github.com/benjamn/reify/commit/8b8694792b40fecaf362cdd60040a075621d73a1
* Support for a `reify.parser` option in `package.json`: https://github.com/benjamn/reify/commit/23c4b9d438bc7a74504fded8056b758672cd6705
* An example package that uses the `reify.parser` option: https://github.com/benjamn/reify/commit/525b464bf7734477ee8ea5fd00fa65c6293f9f49

I still need to update the `README.md`, but hopefully these changes will get things started!

**Comment by jdalton** [comment]
Rock 🤘, thank you!
