### ISSUE TITLE
Detect if reify has already been applied.

### ISSUE THREAD

**Issue by jdalton** [benjamn/reify#69]
From slack, I brought up the idea to check if reify has already been applied to avoid re-wrapping or re-wiring. This would feed into a larger versioning item (a plan to support versioning).

I'd like to have reify (of some form) be a prerequisite for Lodash v5.  Because of Lodash's heavy use, and the way reify works *(global hook)*, versioning will be something I'd like to have a path on.

Related loosely to #61.

**Comment by benjamn** [comment]
This is great! So far Meteor has been the primary consumer of Reify-generated code, but I would be very happy to expand the client base.

**Comment by benjamn** [comment]
I am checking if `Module.prototype._compile` has already been wrapped in Node (see [here](https://github.com/benjamn/reify/blob/631f6d9809f973a91c5e0c61f557359cbd560da7/node/compile-hook.js#L8)), but I'm not yet making any attempt to reconcile different versions of Reify.

**Comment by jdalton** [comment]
It looks like you keep a reference to the originally wrapped `_compile` in the `.reified` property so that's good. Since you're already resolving if a package is using reify you also know which version of reify they're requesting. You can have the wrapper basically proxy to the approp version by having each version register with the wrapper and then it just redirects to the approp handler.

**Comment by jdalton** [comment]
I'll look into making a PR for this.

**Comment by jdalton** [comment]
Fixed by #152.
