### ISSUE TITLE
Object.assign use

### ISSUE THREAD

**Issue by jdalton** [benjamn/reify#70]
I noticed you have a `util.assign`. Is the min bar of support Node 4? If so it can be removed for using built-in `Object.assign`. Let me know and I'll create a PR to clean it up.

**Update**
It looks like testing goes back to old old versions like Node 0.8. I'd propose the bar be raised to Node 4 so that things can be cleaned up. This not only effects things like `util` but also the code generated for the `import/export` and other transforms. Other goodies like `Map`, `Set`, `Symbol`, and `WeakMap` become available to you too.

**Comment by jdalton** [comment]
It looks like testing goes back to old old versions like Node 0.8. I'd propose the bar be raised to Node 4 so that things can be cleaned up. This not only effects things like `util` but also the code generated for the `import/export` transforms.

**Comment by jdalton** [comment]
Other goodies like `Map`, `Set`, and `WeakMap` become available to you too.

**Comment by benjamn** [comment]
It would also be nice to generate arrow functions for the `module.import` setters! Method syntax is tempting, but the method name would usually shadow the local variable name (unless you're renaming the imported symbol).

**Comment by jdalton** [comment]
I can baby step PRs (do assign first, then map or set next). Do you have areas to tackle in mind? If you make a list I can help knock them out.

**Comment by jdalton** [comment]
Moved to #76.
