### ISSUE TITLE
opt-out of nested import.

### ISSUE THREAD

**Issue by jdalton** [benjamn/reify#71]
I'm looking to minimize compile time (with things like [a top-level parse](https://github.com/benjamn/reify/issues/68)) and wondering if I could switch things that require more than that (like nested imports) off.

**Comment by benjamn** [comment]
I think using `reify/lib/parsers/top-level.js` via the `reify.parser` option in `package.json` will automatically do this, since there won't be any nested `import` declarations in the AST to visit.

**Comment by jdalton** [comment]
Ah great! I was wondering if that might automatically shake out.
