### ISSUE TITLE
Investigate performance.

### ISSUE THREAD

**Issue by jdalton** [benjamn/reify#79]
I noticed loading various forms of `lodash-es` (over 300+ modules) that there was some performance issues. For the cjs form I babel transpiled lodash-es into a bunch of  cjs modules to load. This is using the top-level parse. Here's the breakdown:
```
NO REIFY CACHE
loading cjs: 242.283ms
loading reify: 48.958ms
loading cjs after reify: 1097.661ms
loading esm: 958.383ms
loading esm.gz: 1017.981ms

REIFY CACHED
loading cjs: 101.361ms
loading esm: 339.643ms
loading esm.gz: 443.355ms
```

**Update:**
You can now run [the benchmark](https://github.com/jdalton/reify-perf-check) in Node 6+ [in the Chrome inspector](https://medium.com/@paul_irish/debugging-node-js-nightlies-with-chrome-devtools-7c4a1b95ae27):
```shell
npm run inspect
```

**Comment by benjamn** [comment]
I bet most of this overhead comes from calling `module.runModuleSetters()` when a module finishes loading. Probably some opportunities for optimization in that method, though I would expect it to be a little slower to call a bunch of setter functions than to just return `module.exports`.

**Comment by jdalton** [comment]
I've put up a repro repo at https://github.com/jdalton/reify-perf-check.

**Comment by jdalton** [comment]
Ah it looks like I missed the config https://github.com/jdalton/reify-perf-check/commit/567dcdb5fe3f405a482ff562334553ed1511bb94.

```
loading cjs: 232.658ms
loading reify: 60.900ms
loading cjs after reify: 150.626ms
loading esm: 344.662ms
loading esm.gz: 387.240ms
```

**Comment by jdalton** [comment]
I'll still look into refining perf but it's no longer has big an issue with the top-level parse.

**Comment by jdalton** [comment]
\cc @RReverser

**Comment by jdalton** [comment]
Oops. I wasn't clearing the cache. The uncached numbers with `top-level` is:
```
loading cjs: 196.085ms
loading reify: 47.104ms
loading cjs after reify: 1074.976ms
loading esm: 920.173ms
loading esm.gz: 996.598ms
```

**Comment by jdalton** [comment]
I've updated the benchmarks with pre-cache and cached results. It looks like there's still work to do.

**Comment by benjamn** [comment]
Just pushed a [commit](https://github.com/benjamn/reify/commit/6dd17d074802f2709b25c42e3530565456669dcf) that returns early from `Entry.prototype.runModuleSetters` when there are no setters to run.

Interestingly, this did not affect performance at all. I even tried making `runModuleSetters` a no-op by always returning early, and still no change. That leads me to believe my hypothesis above is wrong, which is reassuring!

My new hypothesis is that the overhead of checking the Reify cache is what's causing the slowdown.

**Comment by jdalton** [comment]
Ya, I meant to post back that the setters didn't affect much. I tried making writing the cache async but that didn't affect much either.

**Comment by jdalton** [comment]
Updated numbers from @benjamn's commit https://github.com/benjamn/reify/commit/a7a70c9dd11ee39f27c3c5731b47dd9e4b99f50d which avoids parsing most cjs files.
```
NO REIFY CACHE
loading cjs: 217.649ms
loading reify: 51.007ms
loading cjs after reify: 174.903ms
loading esm: 978.029ms
loading esm.gz: 973.033ms

REIFY CACHED
loading cjs: 92.841ms
loading esm: 302.673ms
loading esm.gz: 475.837ms
```

**Comment by jdalton** [comment]
On the pre-cache size I've opened an issue to look at improving things around ast-types. For the post cache scores do you have an idea of what's slowing it down (I assume the cache resolving code or maybe a directory walk if that's something it's doing).

**Comment by jdalton** [comment]
BTW I disabled the cache generation and it reduced the overall compile time by nearly 300ms. Which means a win from a simpler hash may have a big impact.

**Comment by jdalton** [comment]
You can now run [the benchmark](https://github.com/jdalton/reify-perf-check) in Node 6+ [in the Chrome inspector](https://medium.com/@paul_irish/debugging-node-js-nightlies-with-chrome-devtools-7c4a1b95ae27):
```shell
npm run inspect
```

**Comment by jdalton** [comment]
Performance is getting better:
```
REIFY CACHED
loading cjs: 194.580ms
loading esm: 336.867ms

NO REIFY CACHE
loading cjs: 80.568ms
loading reify: 4.049ms
loading cjs after reify: 122.899ms
loading esm: 448.946ms
```

**Comment by jdalton** [comment]
If we reduced loading and cache by 100ms I think we'd be perfect.

**Comment by jdalton** [comment]
Now cached perf is at or below `100ms` :tada: :tada: :tada:
