### ISSUE TITLE
Improve performance of ast-types.

### ISSUE THREAD

**Issue by jdalton** [benjamn/reify#86]
I wanted to bubble up the issue with [Reify's use](https://github.com/benjamn/reify/blob/4eb7442dc45ac786663036913163bf088529981b/lib/compiler.js#L3-L6) of [ast-types](https://github.com/benjamn/ast-types) so that folks like @hzoo (or someone he may recommend) can help.

Related to #79.

**Comment by benjamn** [comment]
Besides performance, removing the `ast-types` dependency would liberate Reify from having to care about the exact set of AST types the parser is using (Esprima, Babylon, etc.), as long as the import/export-related types agree.
