### ISSUE TITLE
Code review notes

### ISSUE THREAD

**Issue by jdalton** [benjamn/reify#90]
I wanted to capture the notes I took during our code review.

## Moved 
- An option to handle proposed syntax (nested import, namespace export) (moved to #100)
- Don't save setter for const exports. (moved to #134)

## Completed
- [x] Check if namespace import is constant and if so the bind isn't needed and it can be const.
- [x] Use arrow functions for module.import and `module.exports`, `module.import`, and `module.importSync`.
- [x] The namespace object should be `Object.create(null)`
- [x] The cache hash - look into mtime + path + version.
- [x] If a module has `import`/`export` add `'use strict'`
- [x] Align setEsModule `__esModule` property non-enumerable
- [x] ~~- Make the uniqueKey a fast property by changing the `:` to a `__` or something similar~~
- [x] ~~Should `addGetters` throw? Yes.~~
- [x] `forEachSetter` (use UNDEFINED lookup)

**Comment by jdalton** [comment]
> Check if namespace import is constant and if so the bind isn't needed and it can be const.

The rules for namespace properties are [here](http://www.ecma-international.org/ecma-262/7.0/#sec-module-namespace-exotic-objects). The property descriptors should be:
```
{ [[Writable]]: true, [[Enumerable]]: true, [[Configurable]]: false }
```
Which means you can create the namespace object and then pass it through [Object.seal](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/seal).

**Comment by jdalton** [comment]
No need to have `Object.defineProperty` for all of them since `Object.seal` will take care of it.

**Comment by benjamn** [comment]
`[[Writable]]: true` though?

**Comment by benjamn** [comment]
I thought that to-do item was more to check if the namespace variable itself could be modified to hold a value different from the original object, which is what the `<setter function>.bind(ns = Object.create(null))` protects against.

**Comment by jdalton** [comment]
> [[Writable]]: true though?

That's what the spec says. I've pinged Brian Terlson to see if it's a spec bug.

> I thought that to-do item was more to check if the namespace variable itself could be changed to a value different from the original object,

Ah ya. Imported identifiers are all `const`.

**Comment by jdalton** [comment]
Ok so, [it's still writable in the draft spec too](http://www.ecma-international.org/ecma-262/7.0/#sec-module-namespace-exotic-objects).

**Comment by jdalton** [comment]
I looked up taking on 
> Make the uniqueKey a fast property by changing the : to a __ or something similar

Tt looks like most all keys are the slow kind because they use file paths. This was a nice to have but not a biggie so ~~crossing it out~~.
